#:schema node_modules/wrangler/config-schema.json
name = "bolt-diy-v2"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"
send_metrics = false

[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = "./build/client"
entry-point = "functions/[[path]].js"
